#pragma once

// Which address each replaced function has in the game being built.
//
// Almost every native replaces an SDK routine that every game carries at its
// own address, so the addresses belong to the game, not to the library. A game
// supplies a table of them, generated by scanning its own code, and each
// registration looks itself up by name. A function the table does not mention
// is one that game does not have, or one the scan could not find: the
// registration is dropped and the game's own translated code runs.

#if !__has_include("native_bindings.h")
#error "<wiinx/cpu/bindings.hpp> is part of the runtime: build with the cpu section on the include path."
#endif

#include "native_bindings.h"
