using System.IO;
using System.Text;
using Translator.Core.IO;

namespace Translator.Core.CodeGen;

/// <summary>
/// Generates runtime configuration metadata for the C++ runtime harness.
/// This includes critical architectural values like SDA base pointers that
/// must be initialized before any translated code can execute.
/// </summary>
public sealed class RuntimeConfigGenerator
{
    /// <summary>
    /// Generates a C++ header file containing runtime configuration metadata. SDA bases come from the
    /// project manifest, not from scanning the boot code: they're data pinned to the DOL's SHA-256, and
    /// guessing them from section midpoints could silently produce a wrong runtime.
    /// </summary>
    /// <summary>
    /// The MEM1 arena start for an image ending at <paramref name="imageEnd"/>: the SDK
    /// linker puts a 64 KiB stack after the image (8-byte aligned), and OSInit rounds
    /// what follows up to 32. Checked on Mario Kart Wii (0x80399180) and Mega Man 9
    /// (0x80500280, whose __init_registers sets r1 = 0x80500278).
    /// </summary>
    public static uint ArenaLoFor(uint imageEnd) =>
        ((((imageEnd + 7u) & ~7u) + 0x10000u) + 31u) & ~31u;

    public static void GenerateConfigHeader(
        uint sda1Base,
        uint sda2Base,
        string outputPath,
        string projectName = "PowerPC DOL",
        uint? entryPoint = null,
        uint? arenaLo = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"// AUTO-GENERATED for {projectName}");
        sb.AppendLine("// DO NOT EDIT THIS FILE MANUALLY");
        sb.AppendLine("//");
        sb.AppendLine("// The runtime loads these into r2/r13 before executing any translated code,");
        sb.AppendLine("// and starts the guest at the entry point below.");
        sb.AppendLine();
        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine();
        sb.AppendLine("namespace RuntimeConfig {");
        sb.AppendLine();
        sb.AppendLine("// PowerPC ABI Small Data Area base pointers");
        sb.AppendLine("// These MUST be loaded into r2 and r13 before executing any translated code.");
        sb.AppendLine();

        // SDA1 (r13) - read/write small data
        sb.AppendLine($"// _SDA_BASE_ (r13): Base pointer for .sdata/.sbss sections");
        sb.AppendLine($"constexpr uint32_t SDA1_BASE = 0x{sda1Base:X8}u;  // memory.sda_base");
        sb.AppendLine();

        // SDA2 (r2) - read-only small data
        sb.AppendLine($"// _SDA2_BASE_ (r2): Base pointer for .sdata2/.sbss2 sections");
        sb.AppendLine($"constexpr uint32_t SDA2_BASE = 0x{sda2Base:X8}u;  // memory.sda2_base");
        sb.AppendLine();


        if (entryPoint is { } entry)
        {
            sb.AppendLine();
            sb.AppendLine("// Where the guest starts. Taken from this game's DOL, not assumed: the");
            sb.AppendLine("// runtime used to begin at a fixed address, which was one game's.");
            sb.AppendLine($"constexpr uint32_t ENTRY_POINT = 0x{entry:X8}u;  // translation.entry_points[0]");
            sb.AppendLine("#define RUNTIME_CONFIG_HAS_ENTRY_POINT 1");
        }
        if (arenaLo is { } arena)
        {
            sb.AppendLine();
            sb.AppendLine("// Where the MEM1 arena begins: past the image and its 64 KiB stack, as");
            sb.AppendLine("// OSInit rounds the linker's __ArenaLo.");
            sb.AppendLine($"constexpr uint32_t ARENA_LO = 0x{arena:X8}u;");
            sb.AppendLine("#define RUNTIME_CONFIG_HAS_ARENA_LO 1");
        }
        sb.AppendLine();
        sb.AppendLine("} // namespace RuntimeConfig");
        sb.AppendLine();

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        FileOutput.WriteTextIfChanged(outputPath, sb.ToString());
    }
}
