#pragma once

// Where each replaced function lives in the game being built.
//
// The runtime replaces ~580 guest functions with native code. Every
// registration names the address that function has in the game whose code was
// read to identify it - its reference address - and those are collected into
// one table by tools/wiinx-reference-bindings. Almost all of them are Nintendo
// SDK routines that every Wii game carries, at its own addresses, so the
// address belongs to the game and not to the runtime.
//
// Every game therefore supplies a table, generated by wiinx-make-bindings from
// what wiinx-scan found in it, and every registration looks itself up here.
// The lookup is by reference address, not by name: one native often replaces
// several guest functions - the six cache operations are one no-op - and a
// table keyed by name could only bind the first of them.
//
// A registration the table does not mention is one this game does not have, or
// one we could not find in it: Resolve reports 0 and the registration is
// dropped, so the game's own translated code runs rather than a replacement
// pointed at the wrong address. A game with no table at all binds nothing, for
// the same reason: the addresses written at the call sites are another game's.

#include <cstddef>
#include <cstdint>

namespace NativeBindings {

struct Binding {
    std::uint32_t reference; // the address the registration was written from
    std::uint32_t address;   // where that same function is in this game
};

// The game's table, sorted by reference address. The default is empty; a game
// links a generated file defining these instead (see wiinx-make-bindings).
extern const Binding* Table() noexcept;
extern std::size_t TableSize() noexcept;

// True when a game supplied a table at all.
inline bool Present() noexcept { return TableSize() != 0; }

// The address to register at, for the registration written at `reference`.
// Zero when this game has no table, or has one that does not mention it.
inline std::uint32_t Resolve(std::uint32_t reference) noexcept {
    const std::size_t count = TableSize();
    if (count == 0) {
        return 0;
    }
    const Binding* table = Table();
    std::size_t low = 0;
    std::size_t high = count;
    while (low < high) {
        const std::size_t middle = low + (high - low) / 2;
        if (table[middle].reference == reference) {
            return table[middle].address;
        }
        if (table[middle].reference < reference) {
            low = middle + 1;
        } else {
            high = middle;
        }
    }
    // Not in this game, or not found in it: no replacement, so the game's own
    // code runs. Better a slow original than a fast wrong one.
    return 0;
}

}  // namespace NativeBindings
